const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  getRecordingsDir: () => ipcRenderer.invoke('get-recordings-dir'),
  openRecordingsDir: () => ipcRenderer.invoke('open-recordings-dir'),
  pickRecordingsDir: () => ipcRenderer.invoke('pick-recordings-dir'),
  exportWhatsapp: (file) => ipcRenderer.invoke('export-whatsapp', { file }),
  listRecordings: () => ipcRenderer.invoke('list-recordings'),
  revealFile: (file) => ipcRenderer.invoke('reveal-file', { file }),
  openFile: (file) => ipcRenderer.invoke('open-file', { file }),
  deleteRecording: (file) => ipcRenderer.invoke('delete-recording', { file }),
  recordStart: (url, name, durationSec) => ipcRenderer.invoke('record-start', { url, name, durationSec }),
  recordStop: (id) => ipcRenderer.invoke('record-stop', { id }),
  recordList: () => ipcRenderer.invoke('record-list'),
  onRecordStopped: (cb) => ipcRenderer.on('record-stopped', (_e, data) => cb(data)),
  scheduleAdd: (url, name, startAt, durationSec) => ipcRenderer.invoke('schedule-add', { url, name, startAt, durationSec }),
  scheduleList: () => ipcRenderer.invoke('schedule-list'),
  scheduleCancel: (id) => ipcRenderer.invoke('schedule-cancel', { id }),
  onScheduleFired: (cb) => ipcRenderer.on('schedule-fired', (_e, d) => cb(d)),
  onScheduleError: (cb) => ipcRenderer.on('schedule-error', (_e, d) => cb(d)),
  relayStart: (url, name) => ipcRenderer.invoke('relay-start', { url, name }),
  relayStop: () => ipcRenderer.invoke('relay-stop'),
  liveTranscodeTune: (url, name) => ipcRenderer.invoke('live-transcode-tune', { url, name }),
  relayStopIdle: () => ipcRenderer.invoke('relay-stop-idle'),
  probeStream: (url) => ipcRenderer.invoke('probe-stream', { url }),
  onRelayStopped: (cb) => ipcRenderer.on('relay-stopped', (_e, data) => cb(data)),
  tunnelStart: () => ipcRenderer.invoke('tunnel-start'),
  tunnelStop: () => ipcRenderer.invoke('tunnel-stop'),
  onTunnelStatus: (cb) => ipcRenderer.on('tunnel-status', (_e, d) => cb(d)),
  onTunnelStopped: (cb) => ipcRenderer.on('tunnel-stopped', (_e, d) => cb(d)),
  onMainError: (cb) => ipcRenderer.on('main-error', (_e, d) => cb(d)),
  checkUpdate: () => ipcRenderer.invoke('check-update'),
  downloadStart: (url, name, ext) => ipcRenderer.invoke('download-start', { url, name, ext }),
  downloadCancel: (id) => ipcRenderer.invoke('download-cancel', { id }),
  onDownloadProgress: (cb) => ipcRenderer.on('download-progress', (_e, d) => cb(d)),
  onDownloadDone: (cb) => ipcRenderer.on('download-done', (_e, d) => cb(d)),
  openDownloadsDir: () => ipcRenderer.invoke('open-downloads-dir'),
  listDownloads: () => ipcRenderer.invoke('list-downloads'),
  downloadsDir: () => ipcRenderer.invoke('downloads-dir'),
  epgLookup: (name, tvgId) => ipcRenderer.invoke('epg-lookup', { name, tvgId }),
  epgSearch: (q, limit) => ipcRenderer.invoke('epg-search', { q, limit }),
  setProviderEpg: (url) => ipcRenderer.invoke('set-provider-epg', { url }),
  xmltvStatus: () => ipcRenderer.invoke('xmltv-status'),
  xmltvConfig: (cfg) => ipcRenderer.invoke('xmltv-config', cfg),
  m3uFetch: (url) => ipcRenderer.invoke('m3u-fetch', { url }),
  openExternal: (url) => ipcRenderer.invoke('open-external', { url })
});
